description: " \
Applying DGCNN on NCALTECH101 with subsampling 128 for 500 epoch.
Remove outliers but aug. only for spatial centering and flipping.
Only the learning sceduler is slightly different."
seed: 0
optimize:
  optimizer: Adam
  lr: 1e-3
  lr_scheduler: ReduceLROnPlateau
  mode: min 
  factor: 0.5
  patience: 50
model:
  name: DGCNN
  k: 20
  aggr: max
  num_bins: null #9
  cnn_type: "" #shufflenet_v2_x0_5
  resnet_crop_dimension: null #[224, 224]  # dimension of crop before it goes into classifier
  est_mlp_layers: null #[1, 30, 30, 1] # kernel layers for EST
  est_activation: "" #nn.LeakyReLU(negative_slope=0.1)
  resnet_pretrained: null #False
train:
  epochs: 500
  batch_size: 32
  loss_fn: nn.CrossEntropyLoss()
  profiler: simple
  ckpt_path: null
dataset:
  name: NCALTECH101
  train_percentage: 0.75 # not applicable
  validation_percentage: 0.10 # not applicable
  image_resolution: [180,240]  # dimension of spatial grid  (H x W)
  num_samples_per_class: null
  num_classes: null
  dataset_path: null
  num_workers: 8
transform:
  train:
    transform: True
    spatial_centering: True
    temporal_scale: 1e-5
    num_events_per_sample: 128
    random_flip: 0.5
    scale_limits: [0.75,1.5] #null
    degree_limit: 20 #10  #null
    thresh_quantile: 0.3
    conv_vec_path: 'datasets/NCALTECH101/conv_scores'
    radius_graph:
      transform: null #True
      r: 3
      max_num_neighbors: 32
      add_edge_attr:
        transform: null #True
        cat: null #True
    shift_and_flip:
      transform: False
      max_shift: 20
      p: 0.5
  validation:
    transform: True
    spatial_centering: ${transform.train.spatial_centering}
    temporal_scale: ${transform.train.temporal_scale}
    num_events_per_sample: ${transform.train.num_events_per_sample}
    random_flip: null
    scale_limits: null
    degree_limit: null
    thresh_quantile: ${transform.train.thresh_quantile}
    conv_vec_path: ${transform.train.conv_vec_path}
    radius_graph:
      transform: null #True
      r: 3
      max_num_neighbors: 32
      add_edge_attr:
        transform: null #True
        cat: null #True  
    shift_and_flip:
      transform: False
      max_shift: 20
      p: 0.5
  test:
    transform: True
    spatial_centering: ${transform.train.spatial_centering}
    temporal_scale: ${transform.train.temporal_scale}
    num_events_per_sample: ${transform.train.num_events_per_sample}
    random_flip: null
    scale_limits: null
    degree_limit: null
    thresh_quantile: ${transform.train.thresh_quantile}
    conv_vec_path: ${transform.train.conv_vec_path} 
    radius_graph:
      transform: null #True
      r: 3
      max_num_neighbors: 32
      add_edge_attr:
        transform: null #True
        cat: null #True
    shift_and_flip:
      transform: False
      max_shift: 20
      p: 0.5
wandb:
  log: True
  dir: ./
  experiment_name: 'DGCNN 128 500 epochs with outlier removal (replicate previous)'
  entity: 'haraghi'
  project: 'DGCNN'