description: " \
Applying EST on FAN1VS3 with FIXED 25000 events."
seed: 0
optimize:
  optimizer: Adam
  lr: 1e-4
  lr_scheduler: ReduceLROnPlateau
  mode: min 
  factor: 0.5
  patience: 10
model:
  name: EST
  k: null #20
  aggr: "" #max
  num_bins: 9
  cnn_type: resnet34
  resnet_crop_dimension: [224, 224]  # dimension of crop before it goes into classifier
  est_mlp_layers: [1, 30, 30, 1] # kernel layers for EST
  est_activation: nn.LeakyReLU(negative_slope=0.1)
  resnet_pretrained: True
train:
  epochs: 100
  batch_size: 8
  loss_fn: nn.CrossEntropyLoss()
  profiler: simple
  ckpt_path: null
  multi_val_test_num: 1
dataset:
  name: FAN1VS3
  train_percentage: 0.75 # not applicable
  validation_percentage: 0.10 # not applicable
  image_resolution: [720,1280]  # dimension of spatial grid  (H x W)
  num_samples_per_class: null
  num_classes: null
  dataset_path: "datasets_torch_geometric/FAN1VS3/data_25000_fixed"
  num_workers: 3
transform:
  train:
    transform: False
    spatial_centering: null #True
    temporal_scale: null # 1e-5
    num_events_per_sample: null #1024
    random_num_events_per_sample:
      transform: null #True
      min_num_events: null #8
      max_num_events: null #2048
      inverse_sampling: null #False
    random_flip: null #0.5
    scale_limits: null #[0.75,1.5]
    degree_limit: null #10  #20
    thresh_quantile: null #0.3
    filter_nodes: null #remove_NASL_failed_pixels
    conv_vec_path: 'datasets/NCALTECH101/conv_scores'
    radius_graph:
      transform: null #True
      r: 3
      max_num_neighbors: 32
      add_edge_attr:
        transform: null #True
        cat: null #True
    shift_and_flip:
      transform: False
      max_shift: 20
      p: 0.5
  validation:
    transform: False
    spatial_centering: ${transform.train.spatial_centering}
    temporal_scale: ${transform.train.temporal_scale}
    num_events_per_sample: ${transform.train.num_events_per_sample}
    random_num_events_per_sample:
      transform: null #True
      min_num_events: null #8
      max_num_events: null #2048
      inverse_sampling: null #False
    random_flip: null
    scale_limits: null
    degree_limit: null
    thresh_quantile: ${transform.train.thresh_quantile}
    filter_nodes: null #remove_NASL_failed_pixels 
    conv_vec_path: ${transform.train.conv_vec_path}
    radius_graph:
      transform: null #True
      r: 3
      max_num_neighbors: 32
      add_edge_attr:
        transform: null #True
        cat: null #True  
    shift_and_flip:
      transform: False
      max_shift: 20
      p: 0.5
  test:
    transform: False
    spatial_centering: ${transform.train.spatial_centering}
    temporal_scale: ${transform.train.temporal_scale}
    num_events_per_sample: ${transform.train.num_events_per_sample}
    random_num_events_per_sample:
      transform: null #True
      min_num_events: null #8
      max_num_events: null #2048
      inverse_sampling: null #False
    random_flip: null
    scale_limits: null
    degree_limit: null
    thresh_quantile: ${transform.train.thresh_quantile}
    filter_nodes:  null #remove_NASL_failed_pixels 
    conv_vec_path: ${transform.train.conv_vec_path} 
    radius_graph:
      transform: null #True
      r: 3
      max_num_neighbors: 32
      add_edge_attr:
        transform: null #True
        cat: null #True
    shift_and_flip:
      transform: False
      max_shift: 20
      p: 0.5
pre_transform:
  train:
    transform: True
    num_events_per_sample: 25000
    thresh_quantile: null #0.3
    filter_nodes: null #remove_NASL_failed_pixels
    conv_vec_path: null #'datasets/NCALTECH101/conv_scores'
  validation:
    transform: True
    num_events_per_sample: ${pre_transform.train.num_events_per_sample}
    thresh_quantile: ${pre_transform.train.thresh_quantile}
    filter_nodes: ${pre_transform.train.filter_nodes}
    conv_vec_path: ${pre_transform.train.conv_vec_path}
  test:
    transform: True
    num_events_per_sample: ${pre_transform.train.num_events_per_sample}
    thresh_quantile: ${pre_transform.train.thresh_quantile}
    filter_nodes: ${pre_transform.train.filter_nodes}
    conv_vec_path: ${pre_transform.train.conv_vec_path}
wandb:
  log: True
  dir: ./
  experiment_name: 'EST 25000 (fixed events)'
  entity: 'haraghi'
  project: 'DGCNN'