description: null
seed: null #0
optimize:
  optimizer: null #Adam
  lr: null #0.001
  lr_scheduler: null #ReduceLROnPlateau
  mode: null #min 
  factor: null #0.5
  patience: null #10
  weight_decay: null #0.0001
model:
  name: null #DGCNN2
  k: null #50
  aggr: null #max
  num_bins: null #9
  cnn_type: null #""
  resnet_crop_dimension: null # [224, 224]  # dimension of crop before it goes into classifier
  est_mlp_layers: null # [1, 30, 30, 1] # kernel layers for EST
  est_activation: null # nn.LeakyReLU(negative_slope=0.1)
  resnet_pretrained: null #True
train:
  epochs: null #200
  batch_size: null #32
  loss_fn: null #nn.NLLLoss()
  profiler: null #simple
  ckpt_path: null
  multi_val_test_num: null #1
  default_root_dir: null
auto_resume:
  sbatch_folder: null
  num_repeat: null
dataset:
  name: null #NASL
  train_percentage: null #0.75 # not applicable
  validation_percentage: null #0.10 # not applicable
  image_resolution: null #[180,240]  # dimension of spatial grid  (H x W)
  num_samples_per_class: null
  num_classes: null
  dataset_path: null
  num_workers: null #4
transform:
  train:
    transform: null #True
    spatial_centering: null #True
    temporal_scale: null #1e-5
    num_events_per_sample: null #32
    random_num_events_per_sample:
      transform: null #True
      min_num_events: null #8
      max_num_events: null #2048
      inverse_sampling: null #False
    random_flip: null #0.5
    scale_limits: null #[0.75,1.5]
    degree_limit: null #10  #20
    thresh_quantile: null #0.3
    filter_nodes: null #remove_NASL_failed_pixels
    conv_vec_path: null #'datasets/NCALTECH101/conv_scores'
    radius_graph:
      transform: null #True
      r: null #3
      max_num_neighbors: null #32
      add_edge_attr:
        transform: null #True
        cat: null #True
    shift_and_flip:
      transform: null #True
      resolution: null #[180,240]
      max_shift: null #20
      p: null #0.5
  validation:
    transform: null #True
    spatial_centering: null #False #True
    temporal_scale: null #1e-5
    num_events_per_sample: null #32
    random_num_events_per_sample:
      transform: null #True
      min_num_events: null #8
      max_num_events: null #2048
      inverse_sampling: null #False
    random_flip: null
    scale_limits: null
    degree_limit: null
    thresh_quantile: null #0.3
    filter_nodes: null #remove_NASL_failed_pixels 
    conv_vec_path: null #'datasets/NCALTECH101/conv_scores'
    radius_graph:
      transform: null #True
      r: null #3
      max_num_neighbors: null #32
      add_edge_attr:
        transform: null #True
        cat: null #True  
    shift_and_flip:
      transform: null #True
      resolution: null #[180,240]
      max_shift: null #20
      p: null #0.5
  test:
    transform: null #True
    spatial_centering: null #False #True
    temporal_scale: null #1e-5
    num_events_per_sample: null #32
    random_num_events_per_sample:
      transform: null #True
      min_num_events: null #8
      max_num_events: null #2048
      inverse_sampling: null #False
    random_flip: null
    scale_limits: null
    degree_limit: null
    thresh_quantile: null #0.3
    filter_nodes:  null #remove_NASL_failed_pixels 
    conv_vec_path: null #'datasets/NCALTECH101/conv_scores'  
    radius_graph:
      transform: null #True
      r: null #3
      max_num_neighbors: null #32
      add_edge_attr:
        transform: null #True
        cat: null #True
    shift_and_flip:
      transform: null #True
      resolution: null #[180,240]
      max_shift: null #20
      p: null #0.5
pre_transform:
  train:
    transform: null #True
    num_events_per_sample: null #32
    thresh_quantile: null #0.3
    filter_nodes: null #remove_NASL_failed_pixels
    conv_vec_path: null #'datasets/NCALTECH101/conv_scores'
  validation:
    transform: null #True
    num_events_per_sample: null #32
    thresh_quantile: null #0.3
    filter_nodes: null #remove_NASL_failed_pixels 
    conv_vec_path: null #'datasets/NCALTECH101/conv_scores'
  test:
    transform: null #True
    num_events_per_sample: null #32
    thresh_quantile: null #0.3
    filter_nodes:  null #remove_NASL_failed_pixels 
    conv_vec_path: null #'datasets/NCALTECH101/conv_scores'  
wandb:
  log: null #True
  offline: null #False
  dir: null #./
  id: null 
  experiment_name: null #""
  entity: null #'haraghi'
  project: null #'DGCNN'