description: ""
seed: 0
optimize:
  optimizer: Adam
  lr: null # 0.001
  lr_scheduler: "" # ReduceLROnPlateau
  mode: min 
  factor: null #0.5
  patience: null #20
model:
  name: "" #NVS2GRAPH
  k: null #20
  aggr: "" #max
  num_bins: null
  resnet_crop_dimension: null #[224, 224]  # dimension of crop before it goes into classifier
  est_mlp_layers: null #[1, 30, 30, 1] # kernel layers for EST
  est_activation: "" #nn.LeakyReLU(negative_slope=0.1)
  resnet_pretrained: null #True
train:
  epochs: null #100
  batch_size: null #32
  loss_fn: "" #nn.NLLLoss()
  profiler: simple
  ckpt_path: null
dataset:
  name: null
  train_percentage: 0.75 # not applicable
  validation_percentage: 0.10 # not applicable
  image_resolution: null # [180,240]  # dimension of spatial grid  (H x W)
  num_samples_per_class: null
  num_classes: null
  dataset_path: null
  num_workers: 4
transform:
  train:
    transform: null #True
    spatial_centering: null #True
    temporal_scale: null # 1e-5
    num_events_per_sample: null #1024
    random_flip: null #0.5
    scale_limits: null #[0.75,1.5]
    degree_limit: null #10  #20
    thresh_quantile: null #0.3
    conv_vec_path: 'datasets/NCALTECH101/conv_scores'
    radius_graph:
      transform: null #True
      r: 3
      max_num_neighbors: 32
      add_edge_attr:
        transform: null #True
        cat: nul #True
  validation:
    transform: null #True
    spatial_centering: null #False #True
    temporal_scale: null #1e-5
    num_events_per_sample: null #1024
    random_flip: null
    scale_limits: null
    degree_limit: null
    thresh_quantile: null #0.3
    conv_vec_path: 'datasets/NCALTECH101/conv_scores'
    radius_graph:
      transform: null #True
      r: 3
      max_num_neighbors: 32
      add_edge_attr:
        transform: null #True
        cat: nul #True         
  test:
    transform: null #True
    spatial_centering: null #False #True
    temporal_scale: null #1e-5
    num_events_per_sample: null #1024
    random_flip: null
    scale_limits: null
    degree_limit: null
    thresh_quantile: null #0.3
    conv_vec_path: 'datasets/NCALTECH101/conv_scores'  
    radius_graph:
      transform: null #True
      r: 3
      max_num_neighbors: 32
      add_edge_attr:
        transform: null #True
        cat: null #True
wandb:
  log: null #true
  dir: ./
  experiment_name: ''
  entity: 'haraghi'
  project: 'DGCNN'