seed: 0
optimize:
  optimizer: Adam
  lr: 0.001
  lr_scheduler: ReduceLROnPlateau
  mode: min 
  factor: 0.5
  patience: 20
model:
  name: NVS2GRAPH
  k: 20
  aggr: max
train:
  epochs: 100
  batch_size: 32
  profiler: simple
  ckpt_path: null
dataset:
  name: NASL
  train_percentage: 0.75 # not applicable
  validation_percentage: 0.10 # not applicable
  num_samples_per_class: null
  num_classes: null
  dataset_path: null
  num_workers: 4
transform:
  train:
    transform: True
    spatial_centering: False #True
    temporal_scale: 5e-6
    num_events_per_sample: 1024
    random_flip: null #0.5
    scale_limits: null #[0.75,1.5]
    degree_limit: null #10  #20
    thresh_quantile: null #0.3
    conv_vec_path: '/tudelft.net/staff-bulk/ewi/insy/VisionLab/maraghi/event-based-GNN/datasets/NCALTECH101/conv_scores'
    radius_graph:
      transform: True
      r: 3
      max_num_neighbors: 32
      add_edge_attr:
        transform: True
        cat: True
  validation:
    transform: True
    spatial_centering: False #True
    temporal_scale: 5e-6
    num_events_per_sample: 1024
    random_flip: null
    scale_limits: null
    degree_limit: null
    thresh_quantile: null #0.3
    conv_vec_path: '/tudelft.net/staff-bulk/ewi/insy/VisionLab/maraghi/event-based-GNN/datasets/NCALTECH101/conv_scores'
    radius_graph:
      transform: True
      r: 3
      max_num_neighbors: 32
      add_edge_attr:
        transform: True
        cat: True         
  test:
    transform: True
    spatial_centering: False #True
    temporal_scale: 5e-6
    num_events_per_sample: 1024
    random_flip: null
    scale_limits: null
    degree_limit: null
    thresh_quantile: null #0.3
    conv_vec_path: '/tudelft.net/staff-bulk/ewi/insy/VisionLab/maraghi/event-based-GNN/datasets/NCALTECH101/conv_scores'  
    radius_graph:
      transform: True
      r: 3
      max_num_neighbors: 32
      add_edge_attr:
        transform: True
        cat: True
wandb:
  log: true
  dir: ./
  experiment_name: ''
  entity: 'haraghi'
  project: 'DGCNN'