program: train.py
method: random
name: test-25000-tonic-dataset-250epochs
project: EST-DVSGESTURE-HP-sweep
entity: haraghi
description: |
  HP tuning for DVSGESTURE_TONIC dataset with 25000 events per sample.
metric:
  goal: maximize
  name: val/acc/mean
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "cfg_path=cfg_folder/EST_DVSGESTURE_TONIC_wandb_sweep.yaml"
  - "transform.train.num_events_per_sample=25000"
  - "wandb.experiment_name=''"
  - "wandb.log=False"
  - "wandb.offline=False"
  - ${args_no_hyphens}
parameters:
  seed:
    values:
      - 0
  optimize:
    parameters:
      lr:
        values:
          - 1e-6
          - 5e-6
          - 1e-5
          - 5e-5
          - 1e-4
          - 5e-4
          - 1e-3
          - 5e-3
          - 1e-2
      patience:
        values:
          # - 10
          # - 20
          - 40
          # - 80
      weight_decay:
        values:
          - 0
          - 1e-5
          - 1e-4
          - 1e-3
          - 1e-2
  train:
    parameters:
      epochs:
        values:
          # - 100
          - 250
          # - 500
      batch_size:
        values:
          - 8
          - 16
          - 32
          - 64
