program: train.py
method: random
name: NASL_varyinig_sparsity
project: FINAL-NASL-varyinig-sparsity
entity: haraghi
description: |
  Final varying sparsity for NASL dataset.
metric:
  goal: maximize
  name: val/acc/mean
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
parameters:
  cfg_path:
    values:
      - "cfg_folder/EST_NASL_wandb_sweep.yaml"
  # seed:
  #   values:
  #     - 0
  # transform:
  #   parameters:
  #     train:
  #       parameters:
  #         num_events_per_sample:
  #           values:
  #             - 8
  optimize:
    parameters:
      lr:
        values:
          # - 1e-6
          # - 5e-6
          # - 1e-5
          # - 5e-5
          - 1e-4
          # - 5e-4
          # - 1e-3
          # - 5e-3
          # - 1e-2
      patience:
        values:
          # - 10
          - 20
          # - 40
          # - 80
      weight_decay:
        values:
          - 0
          # - 1e-4
          # - 1e-3
          # - 1e-2
          # - 1e-1
  train:
    parameters:
      epochs:
        values:
          - 100
          # - 250
          # - 500
      batch_size:
        values:
          # - 1
          # - 8
          # - 16
          - 32
          # - 64
