name: subsampling
project: TOS_2D_Harris_NCARS_100x120_42s
entity: haraghi
description: |
  Spatial, temporal, and random subsampling bandwidth calculation for NCARS dataset.
cfg_path: "cfg_folder/sampling_bandwidth_NCARS.yaml"
sweep_parameters:
  seed:
      - 42
      - 420
      - 4200
      - 42000
      - 420000
      - 4200000
      # - 12
      # - 120
      # - 1200
      # - 12000
      # - 120000
      # - 1200000
      # - 24
      # - 240
      # - 2400
      # - 24000
      # - 240000
      # - 2400000
      # - 5001
      # - 5002
      # - 5003
      # - 5004
      # - 5005
      # - 5006
      # - 5007
      # - 5008
      # - 5009
      # - 5010
      # - 5011
      # - 5012
      # - 5013
      # - 5014
      # - 5015
      # - 5016
      # - 5017
      # - 5018
      # - 5019
      # - 5020
      # - 5021
      # - 5022
      # - 5023
      # - 5024
      # - 5025
      # - 5026
      # - 5027
      # - 5028
      # - 5029
      # - 5030
      # - 5031
      # - 5032
      # - 5033
      # - 5034
      # - 5035
      # - 5036
      # - 5037
      # - 5038
      # - 5039
      # - 5040
      # - 5041
      # - 5042
      # - 5043
      # - 5044
      # - 5045
      # - 5046
      # - 5047
      # - 5048
      # - 5049
      # - 5050
  transform:
    train:
  ############################################################################################################
      # spatial_subsampling:
      #   transform: True
      #   h_r:
      #     - 2
      #     - 3
      #     - 6
      #     - 8
      #     - 12
      #     - 16
      #   v_r:
      #     - 2
      #     - 4
      #     - 6
      #     - 10
      #     - 15
      #     - 25
      #   # h_r_offset:
      #   #   - 1
      #   #   - 3
      #   #   - 4
      #   #   - 6
      #   # v_r_offset:
      #   #   - 2
      #   #   - 5
      #   #   - 6
      #   #   - 9
      #   dataset_wide_random_offsets: True
###########################################################################################################
      # spatial_subsampling_random:
      #   transform: True
      #   h_r:
      #     - 2
      #     - 3
      #     - 6
      #     - 8
      #     - 12
      #     - 16
      #   v_r:
      #     - 2
      #     - 4
      #     - 6
      #     - 10
      #     - 15
      #     - 25
  ##########################################################################################################
      # temporal_subsampling:
      #   transform: True
      #   subsampling_ratio:
      #     - 4
      #     - 12
      #     - 36
      #     - 80
      #     - 180
      #     - 400
      #   window_size: 10
      #   fixed_interval: False
      #   # time_offset_coefficient:
      #   #   - 0.1
      #   #   - 0.2
      #   #   - 0.3
      #   #   - 0.4
      #   #   - 0.5
      #   dataset_wide_random_time_offset: True
    ##########################################################################################################
      # temporal_subsampling_random:
      #   transform: True
      #   subsampling_ratio:
      #     - 4
      #     - 12
      #     - 36
      #     - 80
      #     - 180
      #     - 400
      #   window_size: 10
      #   fixed_interval: False
  ###########################################################################################################
      # random_ratio_subsampling:
      #   - 0.25
      #   - 0.0833333
      #   - 0.0277777
      #   - 0.0125
      #   - 0.0055555
      #   - 0.0025
###########################################################################################################
      # spatiotemporal_filtering_subsampling:
      #   transform: True
      #   tau: 30
      #   filter_size: 7
      #   sampling_threshold: 
      #     - 0.0025
      #     - 0.006
      #     - 0.015
      #     - 0.033
      #     - 0.1
      #     - 0.3
      #     # - 0.25
      #     # - 0.0833333
      #     # - 0.0277777
      #     # - 0.0125
      #     # - 0.0055555
      #     # - 0.0025
      #   normalization_length: null
      #   mean_normalized: True
###########################################################################################################
      tos_2DHarris_subsampling:
        transform: True
        filter_size: 7
        TOS_T: 14
        Harris_block_size: 2
        Harris_ksize: 3
        Harris_k: 0.04
        sampling_threshold: 
          - 11.0
          - 4.0
          - 1.8
          - 1.0
          - 0.6
          - 0.4
        normalization_length: null
        mean_normalized: null
###########################################################################################################
  pre_transform:
    train:
      # baseline_event_count:
      #   transform: True
      #   threshold: 
      #     - 0.750
      #     - 0.750
      #     - 1.000
      #     - 1.000
      #     # - 1.000
      #     # - 1.000
      #   h_r:
      #     - 2
      #     - 3
      #     - 6
      #     - 8
      #     # - 12
      #     # - 16
      #   v_r:
      #     - 2
      #     - 4
      #     - 6
      #     - 10
      #     # - 15
      #     # - 25