name: subsampling
project: Subsamplimg_methods_DVS_GESTURE_TONIC
entity: haraghi
description: |
  Spatial, temporal, and random subsampling bandwidth calculation for DVS-GESTURE TONIC dataset.
cfg_path: "cfg_folder/sampling_bandwidth_DVS_GESTURE_TONIC.yaml"
sweep_parameters:
  seed:
      - 42
      - 420
      - 4200
      - 42000
      - 420000
      - 4200000
      # - 12
      # - 120
      # - 1200
      # - 12000
      # - 120000
      # - 1200000
      # - 24
      # - 240
      # - 2400
      # - 24000
      # - 240000
      # - 2400000
  transform:
    train:
  ############################################################################################################
      # spatial_subsampling:
      #   transform: True
      #   h_r:
      #     - 2
      #     - 3
      #     - 6
      #     - 8
      #     - 12
      #   v_r:
      #     - 2
      #     - 4
      #     - 6
      #     - 10
      #     - 15
  ##########################################################################################################
      # temporal_subsampling:
      #   transform: True
      #   subsampling_ratio:
      #     - 4
      #     - 12
      #     - 36
      #     - 80
      #     - 180
      #   window_size: 10
  ###########################################################################################################
      # random_ratio_subsampling:
      #   - 0.25
      #   - 0.0833333
      #   - 0.0277777
      #   - 0.0125
      #   - 0.0055555
###########################################################################################################
      spatiotemporal_filtering_subsampling:
        transform: True
        tau: 30
        filter_size: 7
        sampling_threshold: 
          - 0.004
          - 0.009
          - 0.026
          - 0.086
          - 0.216
        normalization_length: null

