program: bandwidth_calculation.py
method: grid
name: spatial_subsampling
project: Subsamplimg-vs-bandwidth-NASL
entity: haraghi
description: |
  Spatial, temporal, and random subsampling bandwidth calculation for NCARS dataset.
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
parameters:
  cfg_path:
    values:
      - "cfg_folder/sampling_bandwidth_NASL.yaml"
  # seed:
  #   values:
  #     - 0
  transform:
    parameters:
      train:
        parameters:
          spatial_subsampling:
            parameters:
              transform:
                value: True
              h_r:
                distribution: q_uniform
                min: 2
                max: 11
                q: 2
              v_r:
                distribution: q_uniform
                min: 2
                max: 11
                q: 2
          # temporal_subsampling:
          #   parameters:
          #     transform:
          #       value: True
          #     subsampling_ratio:
          #       min: 2
          #       max: 20
          #     window_size:
          #       value: 10
          # random_ratio_subsampling:
          #   distribution: q_uniform
          #   min: 0.05
          #   max: 0.5
          #   q: 0.05
  train:
    parameters:
      batch_size:
        values:
          # - 1
          - 8
          # - 16
          # - 32
          # - 64
          # - 100
