name: subsampling
project: Spatial_with_offset_DVS_GESTURE_TONIC
entity: haraghi
description: |
  Spatial, temporal, and random subsampling bandwidth calculation for DVS-GESTURE TONIC dataset.
cfg_path: "cfg_folder/sampling_bandwidth_DVS_GESTURE_TONIC.yaml"
sweep_parameters:
  seed:
      - 42
      - 420
      - 4200
      - 42000
      - 420000
      - 4200000
      - 12
      - 120
      - 1200
      - 12000
      - 120000
      - 1200000
      # - 24
      # - 240
      # - 2400
      # - 24000
      # - 240000
      # - 2400000
      # - 5001
      # - 5002
      # - 5003
      # - 5004
      # - 5005
      # - 5006
      # - 5007
      # - 5008
      # - 5009
      # - 5010
      # - 5011
      # - 5012
      # - 5013
      # - 5014
      # - 5015
      # - 5016
      # - 5017
      # - 5018
      # - 5019
      # - 5020
      # - 5021
      # - 5022
      # - 5023
      # - 5024
      # - 5025
      # - 5026
      # - 5027
      # - 5028
      # - 5029
      # - 5030
      # - 5031
      # - 5032
      # - 5033
      # - 5034
      # - 5035
      # - 5036
      # - 5037
      # - 5038
      # - 5039
      # - 5040
      # - 5041
      # - 5042
      # - 5043
      # - 5044
      # - 5045
      # - 5046
      # - 5047
      # - 5048
      # - 5049
      # - 5050
  transform:
    train:
  ############################################################################################################
      spatial_subsampling:
        transform: True
        h_r:
          # - 2
          # - 3
          # - 6
          - 8
          # - 12
        v_r:
          # - 2
          # - 4
          # - 6
          - 10
          # - 15
        h_r_offset:
          - 1
          - 3
          - 4
          - 6
        v_r_offset:
          - 2
          - 5
          - 6
          - 9
  ##########################################################################################################
      # temporal_subsampling:
      #   transform: True
      #   subsampling_ratio:
      #     - 4
      #     - 12
      #     - 36
      #     - 80
      #     - 180
          # - 400
        # window_size: 10
  ###########################################################################################################
      # random_ratio_subsampling:
        # - 0.25
        # - 0.0833333
        # - 0.0277777
        # - 0.0125
        # - 0.0055555
        # - 0.0025
###########################################################################################################
      # spatiotemporal_filtering_subsampling:
      #   transform: True
      #   tau: 30
      #   filter_size: 7
      #   sampling_threshold: 
      #     - 0.0018
      #     # - 0.004
      #     # - 0.009
      #     # - 0.026
      #     # - 0.086
      #     # - 0.216
      #   normalization_length: null

