program: train.py
method: random
name: multiple-seed-multiple-event-numbers-same-HP-set
project: EST-DVSGESTURE-HP-sweep-InMemory
entity: haraghi
description: |
  HP tuning for DVSGESTURE_TONIC dataset.
metric:
  goal: maximize
  name: val/acc/mean
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
parameters:
  cfg_path:
    values:
      - "cfg_folder/EST_DVSGESTURE_TONIC_wandb_sweep.yaml"
  # seed:
  #   values:
  #     - 0
  # transform:
  #   parameters:
  #     train:
  #       parameters:
  #         num_events_per_sample:
  #           values:
  #             - 64
  optimize:
    parameters:
      lr:
        values:
          - 1e-6
          - 5e-6
          - 1e-5
          - 5e-5
          - 1e-4
          - 5e-4
          - 1e-3
          - 5e-3
          - 1e-2
      patience:
        values:
          # - 10
          # - 20
          - 40
          # - 80
      weight_decay:
        values:
          - 0
          - 1e-5
          - 1e-4
          - 1e-3
          - 1e-2
  train:
    parameters:
      epochs:
        values:
          # - 100
          - 250
          # - 500
      batch_size:
        values:
          - 1
          - 4
          - 8
          - 16
          - 32
          - 64
